services:
  - type: web
    name: rakhtsetu-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn server:app -w 4 -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: RAKHTSETU_KEY
        generateValue: true
